import os

Import('env')

sources = [
    'CriticalEdge.cpp',
    'CriticalGraph.cpp',
    'CriticalGraphReader.cpp',
    'CriticalGraphWriter.cpp',
    'CriticalNode.cpp',
    'CriticalPath.cpp',
]

Return(['sources'])
