
import os.path


Import(['env', 'tibeecomparelib'])

target = 'tibeereport'

libs = [
    tibeecomparelib,
    'delorean',
    'tigerbeetle',
    'boost_program_options',
    'boost_filesystem',
    'boost_thread',
    'boost_system',
    'boost_regex',
    'yaml-cpp',
    'leveldb',
    'bfd',
]

sources = [
    'main.cpp',
    'TibeeReport.cpp',
    'WriteExecutions.cpp',
]

app_env = env.Clone()

app_env.Append(LIBS=libs)
app_env.ParseConfig('pkg-config --cflags glib-2.0')

app = app_env.Program(target=target, source=sources)

Return('app')
