
import os.path

Import(['env',])

sources = [
    'AbstractStacks.cpp',
    'ExecutionsBuilder.cpp',
    'ExecutionsDb.cpp',
    'GenerateExecutionGraph.cpp',
    'GetExecutionSegments.cpp',
    'StackItem.cpp',
    'StacksBuilder.cpp',
    'StacksFromDisk.cpp',
    'StacksReader.cpp',
    'StacksWriter.cpp',
]

Return('sources')
