import os

Import('env')

sources = [
    'AbstractMqSocket.cpp',
    'MessageDecoder.cpp',
    'MessageEncoder.cpp',
    'MqContext.cpp',
    'MqMessage.cpp',
]

env.ParseConfig('pkg-config --cflags --libs libzmq')

Return(['sources'])
