
import os.path

Import(['env',])

sources = [
    'AbstractExecutionBlock.cpp',
    'ExecutionBlock.cpp',
    'PunchBlock.cpp',
    'SchedWakeupBlock.cpp',
    'SyscallOnlyBlock.cpp',
    'ThreadNameBlock.cpp',
]

Return('sources')
