
import os.path

Import(['env',])

sources = [
    'AbstractExecutionBlock.cpp',
    'ExecutionBlock.cpp',
    'ProfilerBlock.cpp',
    'PunchBlock.cpp',
    'SchedWakeupBlock.cpp',
]

Return('sources')
