import os


Import('root_env')

env = root_env.Clone()

env.Append(CPPPATH=['#/src'])

tibeecompare = SConscript(os.path.join('tibeecompare', 'SConscript'),
                          exports=['env'])

Return(['tibeecompare',])